from typing import Any
"""
board Pimoroni Keybow 2040
https://circuitpython.org/boards/pimoroni_keybow2040
"""
  board.TX: Any = ...
  GP0: Any = ...
  RX: Any = ...
  GP1: Any = ...
  INT: Any = ...
  SDA: Any = ...
  SCL: Any = ...
  SW0: Any = ...
  SW1: Any = ...
  SW2: Any = ...
  SW3: Any = ...
  SW4: Any = ...
  SW5: Any = ...
  SW6: Any = ...
  SW7: Any = ...
  SW8: Any = ...
  SW9: Any = ...
  SW10: Any = ...
  SW11: Any = ...
  SW12: Any = ...
  SW13: Any = ...
  SW14: Any = ...
  SW15: Any = ...
  USER_SW: Any = ...
  def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board designated SDA and SCL pins. It is a singleton."""
    ...

  def UART() -> busio.UART:
    """Returns the `busio.UART` object for the board designated TX and RX pins. It is a singleton.

    The object created uses the default parameter values for `busio.UART`. If you need to set
    parameters that are not changeable after creation, such as ``receiver_buffer_size``,
    do not use `board.UART()`; instead create a `busio.UART` object explicitly with the
    desired parameters."""

